web/router.ex
defmodule Crm.Router do
  use Crm.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Crm.Auth, repo: Crm.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Crm do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", Crm do
    pipe_through [:browser, :authenticate_user]

    resources "/contacts", ContactController
    resources "/users", UserController, only: [:edit, :update]
    get "/groups/:id", ContactController, :groups
    get "/search/contacts", ContactController, :search
  end

  scope "/manage", Crm do
    pipe_through [:browser, :authenticate_user]

    resources "/groups", ContactGroupController, only: [:index, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Crm do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Crm.LayoutView do
  use Crm.Web, :view

  def first_name(%Crm.User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end
end

web/templates/layout/_header.html.eex
<header>
  <!-- navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link "CRM", to: contact_path(@conn, :index), class: "navbar-brand" %>
      </div>
      <!-- /.navbar-header -->
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= render "_search_form.html", conn: @conn %>
          </li>
          <li>
            <%= link to: contact_path(@conn, :new), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-plus"></i>
              Add Contact
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <i class="glyphicon glyphicon-user"></i>
                <%= first_name(@current_user) %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link "Profile", to: user_path(@conn, :edit, @current_user), class: "text-center" %></li>
              <li><%= button "Log out", to: session_path(@conn, :delete, @current_user), method: "delete" %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

web/templates/layout/_search_form.html.eex
<%= form_tag(contact_path(@conn, :search), method: "get", enforce_utf8: false, class: "navbar-form navbar-left", role: "search") do %>
  <div class="input-group">
    <input type="text" name="q" class="form-control" placeholder="Search for...">
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search text-primary"></i></button>
    </span>
  </div>
<% end %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Crm | Manage your contacts with ease!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= if @current_user do %>
      <%= render "_header.html", conn: @conn, current_user: @current_user %>
    <% end %>
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info text-center" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= get_flash(@conn, :info) %>
        </p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger text-center" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= get_flash(@conn, :error) %>
        </p>
      <% end %>
    <div class="container">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= Drab.Client.js(@conn) %>
  </body>
</html>