web/router.ex
defmodule Crm.Router do
  use Crm.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Crm.Auth, repo: Crm.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Crm do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", Crm do
    pipe_through [:browser, :authenticate_user]

    resources "/contacts", ContactController
    resources "/users", UserController, only: [:edit, :update]
    get "/groups/:id", ContactController, :groups
    get "/search/contacts", ContactController, :search
  end

  scope "/manage", Crm do
    pipe_through [:browser, :authenticate_user]

    resources "/groups", ContactGroupController, only: [:index, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Crm do
  #   pipe_through :api
  # end
end

web/models/contact.ex
defmodule Crm.Contact do
  use Crm.Web, :model
  use Arc.Ecto.Schema

  alias Crm.{Repo, Contact}

  schema "contacts" do
    field :name, :string
    field :company, :string
    field :email, :string
    field :phone, :string
    field :address, :string
    field :avatar, Crm.Avatar.Type
    belongs_to :user, Crm.User
    belongs_to :contact_group, Crm.ContactGroup
    has_many :notes, Crm.Note

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :company, :email, :phone, :address, :contact_group_id])
    |> validate_required([:name, :email, :phone, :contact_group_id])
  end

  def file_changeset(struct, params \\ %{}) do
    struct
    |> changeset(params)
    |> cast_attachments(params, [:avatar])
    |> valid_file(params)
  end

  defp valid_file(changeset, params) do
    if Map.has_key?(params, "avatar") do
      extension = ~w(.jpg .jpeg .gif .png)
      message = "Only (.jpg .jpeg .gif .png) files allowed"
      file = params["avatar"].filename
      |> Path.extname
      |> String.downcase

      unless Enum.member?(extension, file) do
        changeset = add_error(changeset, :avatar, message)
      end
      changeset
    else
      changeset
    end
  end

  def all(user_id, params) do
    Contact
    |> where(user_id: ^user_id)
    |> order_by(:name)
    |> preload(:contact_group)
    |> Repo.paginate(params)
  end

  def all_contacts_for_group(group_id, params) do
    Contact
    |> where(contact_group_id: ^group_id)
    |> order_by(:name)
    |> preload(:contact_group)
    |> Repo.paginate(params)
  end

  def search(user_id, search_params, params) do
    from(c in Contact,
      where: c.user_id == ^user_id and ilike(c.name, ^"%#{search_params}%"),
      order_by: c.name,
      preload: :contact_group
    )
    |> Repo.paginate(params)
  end

  def count(user_id) do
    hd Repo.all(
      from c in Contact,
      select: count(c.id),
      where: c.user_id == ^user_id
    )
  end
end

web/controllers/contact_controller.ex
defmodule Crm.ContactController do
  use Crm.Web, :controller
  use Drab.Controller

  alias Crm.{Contact, ContactGroup, Note}

  plug :assign_user_id_to_session when action in [:new]

  def index(conn, params) do
    groups = ContactGroup.all(conn.assigns.current_user.id)
    {contacts, kerosene} = Contact.all(
      conn.assigns.current_user.id,
      params
    )

    render(conn, :index,
      contacts: contacts,
      groups: groups,
      kerosene: kerosene
    )
  end

  def show(conn, params) do
    contacts_count = Contact.count(conn.assigns.current_user.id)
    conn = put_session(conn, :contact_id, String.to_integer(params["id"]))
    {notes, kerosene} = Note.all(params["id"], params)
    groups = ContactGroup.all(conn.assigns.current_user.id)
    contact = Repo.get!(
      Contact, params["id"]
    ) |> Repo.preload([:contact_group, :user])

    if contact.user !== conn.assigns.current_user do
      conn
      |> put_flash(:error, "You are not the owner of that contact.")
      |> redirect(to: "/")
    else
      render(conn, :show,
        contact: contact,
        groups: groups,
        notes: notes,
        kerosene: kerosene,
        contacts_count: contacts_count)
    end
  end

  def search(conn, params) do
    contacts_count = Contact.count(conn.assigns.current_user.id)
    groups = ContactGroup.all(conn.assigns.current_user.id)
    {contacts, kerosene} = Contact.search(
      conn.assigns.current_user.id,
      params["q"],
      params
    )

    render(conn, :search,
      contacts: contacts,
      groups: groups,
      kerosene: kerosene,
      contacts_count: contacts_count
    )
  end

  def groups(conn, params) do
    group_id = String.to_integer(params["id"])
    groups = ContactGroup.all(conn.assigns.current_user.id)
    contacts_count = Contact.count(conn.assigns.current_user.id)
    {contacts, kerosene} = Contact.all_contacts_for_group(
      group_id,
      params
    )

    render(conn, :groups,
      contacts: contacts,
      groups: groups,
      kerosene: kerosene,
      contacts_count: contacts_count
    )
  end

  def new(conn, _params) do
    groups = ContactGroup.all(conn.assigns.current_user.id)
    changeset = Contact.changeset(%Contact{})
    render(conn, :new,
      changeset: changeset,
      groups: groups)
  end

  def create(conn, %{"contact" => contact_params}) do
    groups = ContactGroup.all(conn.assigns.current_user.id)
    group = contact_params["contact_group_id"]
    changeset = Contact.file_changeset(%Contact{
      contact_group_id: group,
      user_id: conn.assigns.current_user.id
    }, contact_params)

    case Repo.insert(changeset) do
      {:ok, contact} ->
        unless contact_params["avatar"] == nil do
          Crm.Avatar.store({contact_params["avatar"], contact})
        end

        conn
        |> put_flash(:info, "#{contact.name} created!")
        |> redirect(to: contact_path(conn, :index))
      {:error, changeset} ->
        render(conn, :new, changeset: changeset, groups: groups)
    end
  end

  def edit(conn, %{"id" => id}) do
    groups = ContactGroup.all(conn.assigns.current_user.id)
    contact = Repo.get!(Contact, id) |> Repo.preload(:user)
    changeset = Contact.changeset(contact)

    if contact.user !== conn.assigns.current_user do
      conn
      |> put_flash(:error, "You are not the owner of that contact.")
      |> redirect(to: "/")
    else
      render(conn, :edit,
        contact: contact,
        changeset: changeset,
        groups: groups)
    end
  end

  def update(conn, %{"id" => id, "contact" => contact_params}) do
    groups = ContactGroup.all(conn.assigns.current_user.id)
    contact = Repo.get!(Contact, id) |> Repo.preload(:user)
    changeset = Contact.file_changeset(contact, contact_params)

    if contact.user !== conn.assigns.current_user do
      conn
      |> put_flash(:error, "You are not the owner of that contact.")
      |> redirect(to: "/")
    else
      case Repo.update(changeset) do
        {:ok, contact} ->
          conn
          |> put_flash(:info, "#{contact.name} updated successfully.")
          |> redirect(to: contact_path(conn, :show, contact))
        {:error, changeset} ->
          render(conn, "edit.html",
          contact: contact,
          changeset: changeset,
          groups: groups)
      end
    end
  end

  def delete(conn, %{"id" => id}) do
    contact = Repo.get!(Contact, id) |> Repo.preload(:user)
    if contact.user !== conn.assigns.current_user do
      conn
      |> put_flash(:error, "You are not the owner of that contact.")
      |> redirect(to: "/")
    else
      Repo.delete!(contact)
      unless contact.avatar == nil do
        path = Crm.Avatar.url({contact.avatar, contact}, :thumb)
        :ok = Crm.Avatar.delete({path, contact})
      end

      conn
      |> put_flash(:info, "Contact #{contact.name} deleted successfully.")
      |> redirect(to: contact_path(conn, :index))
    end
  end

  defp assign_user_id_to_session(conn, _) do
    if conn.assigns.current_user do
      conn = put_session(conn, :user_id, conn.assigns.current_user.id)
    end
    conn
  end
end

web/views/contact_view.ex
defmodule Crm.ContactView do
  use Crm.Web, :view
  import Kerosene.HTML

  def gravatar_for(name, email, size \\ 80) do
    gravatar_id = hash(email)
    src ="https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&default=mm"
    img_tag(src, class: "img-circle", alt: name)
  end
  defp md5(str) do
    :crypto.hash(:md5 , str) |> Base.encode16(case: :lower)
  end
  defp hash(email) do
    email
    |> String.strip
    |> String.downcase
    |> md5()
  end

  def avatar_for(contact) do
    src = Crm.Avatar.url({contact.avatar, contact}, :thumb)
    img_tag(src, class: "img-circle", alt: contact.name)
  end

  def avatar(contact) do
    if contact.avatar != nil do
      avatar_for(contact)
    else
      gravatar_for(contact.name, contact.email, 100)
    end
  end

  def active_group?(conn, group_id) do
    group = Integer.to_string(group_id)
    if conn.request_path == contact_path(conn, :groups, group) do
      "list-group-item active"
    else
      "list-group-item"
    end
  end

  def active_group?(conn) do
    if conn.request_path == contact_path(conn, :index) do
      "list-group-item active"
    else
      "list-group-item"
    end
  end

  def multiple_cards(contacts) do
    if length(contacts) > 3 do
      "card"
    end
  end

  def pack?(contacts) do
    if length(contacts) > 3 do
      "pack"
    end
  end
end

web/templates/contact/_contact.html.eex
<div class="col-md-4 col-xs-12 <%= multiple_cards(@contacts) %>">
  <div class="thumbnail">
    <%= link to: contact_path(@conn, :show, @contact) do %>
      <%= if @contact.avatar != nil do %>
        <%= avatar_for(@contact) %>
      <% else %>
        <%= gravatar_for(@contact.name, @contact.email, 100) %>
      <% end %>
    <% end %>
    <div class="caption text-center">
      <%= link to: contact_path(@conn, :show, @contact) do %>
        <h4><%= @contact.name %></h4>
      <% end %>
      <strong><%= @contact.contact_group.name %></strong><br>
      <strong><%= @contact.company %></strong><br>
      <h6><%= @contact.email %></h6>
      <h6><%= @contact.phone %></h6>
      <div class="text-center">
        <%= link to: contact_path(@conn, :show, @contact), class: "btn btn-circle btn-default btn-xs", title: "View" do %>
          <i class="glyphicon glyphicon-eye-open"></i>
        <% end %>
        <%= link to: contact_path(@conn, :edit, @contact), class: "btn btn-circle btn-default btn-xs", title: "Edit" do %>
          <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <%= link to: contact_path(@conn, :delete, @contact), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-circle btn-danger btn-xs", title: "Delete" do %>
          <i class="glyphicon glyphicon-remove"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

web/templates/contact/_form.html.eex
<div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Add Contact</strong>
    </div>
    <div class="panel-body">
      <div class="form-horizontal">
        <div class="row">
          <div class="col-md-8">
            <%= form_for @changeset, @action, [multipart: true], fn f -> %>
              <%= if @changeset.action do %>
                <div class="alert alert-danger">
                <p>Oops, something went wrong! Please check the errors below.</p>
                </div>
              <% end %>
              <div class="form-group">
                <label for="name" class="control-label col-md-3">Name</label>
                <div class="col-md-8">
                  <%= text_input f, :name, class: "form-control" %>
                  <%= error_tag f, :name %>
                </div>
              </div>

              <div class="form-group">
                <label for="company" class="control-label col-md-3">Company</label>
                <div class="col-md-8">
                  <%= text_input f, :company, class: "form-control" %>
                  <%= error_tag f, :company %>
                </div>
              </div>

              <div class="form-group">
                <label for="email" class="control-label col-md-3">Email</label>
                <div class="col-md-8">
                  <%= text_input f, :email, class: "form-control" %>
                  <%= error_tag f, :email %>
                </div>
              </div>

              <div class="form-group">
                <label for="phone" class="control-label col-md-3">Phone</label>
                <div class="col-md-8">
                  <%= text_input f, :phone, class: "form-control" %>
                  <%= error_tag f, :phone %>
                </div>
              </div>

              <div class="form-group">
                <label for="name" class="control-label col-md-3">Address</label>
                <div class="col-md-8">
                  <%= textarea f, :address, rows: 3, class: "form-control" %>
                  <%= error_tag f, :address %>
                </div>
              </div>

              <%= render "_group_form.html", f: f, groups: @groups %>
          </div>
          <div class="col-md-4">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new" style="width: 100px; height: 100px;">
                <%= if @conn.assigns[:contact] do %>
                  <%= avatar(@contact) %>
                <% else %>
                  <%= gravatar_for("Default", "default@default.com", 100) %>
                <% end %>
              </div>
              <div class="fileinput-preview fileinput-exists" style="max-width: 100px; max-height: 100px;"></div>
              <div class="top-space">
                <span class="btn btn-primary btn-file">
                  <span class="fileinput-new">Choose Photo</span>
                  <span class="fileinput-exists">Change</span>
                  <%= file_input f, :avatar %>
                </span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
              <%= error_tag f, :avatar %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <%= submit "Save", class: "btn btn-primary" %>
              <%= link "Cancel", to: contact_path(@conn, :index), class: "btn btn-default" %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

web/templates/contact/_group.html.eex
<%= link to: contact_path(@conn, :groups, @group), class: active_group?(@conn, @group.id) do %>
  <%= @group.name %>
  <span class="badge"><%= length(@group.contacts) %></span>
<% end %>

web/templates/contact/_group_form.html.eex
<div class="form-group">
  <label for="group" class="control-label col-md-3">Group</label>
  <div class="col-md-5">
    <%= select @f,
        :contact_group_id,
        @groups |> Enum.map(&{&1.name, &1.id}),
        prompt: "Select group",
        class: "form-control",
        id: "group"
    %>
    <%= error_tag @f, :contact_group_id %>
  </div>
  <div class="col-md-3">
    <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
  </div>
</div>

<div class="form-group" id="add-new-group">
  <div class="col-md-offset-3 col-md-8">
    <div class="input-group">
      <input type="text" name="new_group" id="new_group" class="form-control">
      <span class="input-group-btn">
        <button drab-click="add_group" class="btn btn-primary">
          <i class="glyphicon glyphicon-plus"></i>
        </button>
      </span>
    </div>
  </div>
</div>

web/templates/contact/_note.html.eex
<article id="article_note_id_<%= @note.id %>" class="list-group-item">
  <div id="note_id_<%= @note.id %>">
    <%= @note.body %>
  </div>
  <div class="text-center">
    <button data-note-id="<%= @note.id %>" drab-click="edit_contact_note" class="btn btn-circle btn-default btn-xs">
      <i class="glyphicon glyphicon-edit"></i>
    </button>
    <button data-note-id="<%= @note.id %>" drab-click="delete_contact_note" class="btn btn-circle btn-danger btn-xs">
      <i class="glyphicon glyphicon-remove"></i>
    </button>
  </div>
</article>

web/templates/contact/_show_contact.html.eex
<div class="col-md-4">
  <div class="thumbnail">
    <%= if @contact.avatar != nil do %>
      <%= avatar_for(@contact) %>
    <% else %>
      <%= gravatar_for(@contact.name, @contact.email, 100) %>
    <% end %>
    <div class="caption text-center">
      <h4><%= @contact.name %></h4>
      <strong><%= @contact.contact_group.name %></strong><br>
      <strong><%= @contact.company %></strong><br>
      <h6><%= @contact.email %></h6>
      <h6><%= @contact.phone %></h6>
      <h6><%= @contact.address %></h6>
      <div class="text-center">
        <button drab-click="add_contact_note" class="btn btn-default btn-sm">
          <i class="glyphicon glyphicon-plus"></i>
          Add Note
        </button>
        <%= link to: contact_path(@conn, :edit, @contact), class: "btn btn-circle btn-default btn-xs", title: "Edit" do %>
          <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <%= link to: contact_path(@conn, :delete, @contact), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-circle btn-danger btn-xs", title: "Delete" do %>
          <i class="glyphicon glyphicon-remove"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

web/templates/contact/edit.html.eex
<div class="col-md-3">
  <div class="list-group">
    <%= link "My Groups", to: contact_group_path(@conn, :index), class: "list-group-item" %>
    <%= link to: contact_path(@conn, :index), class: active_group?(@conn) do %>
      All Contacts
      <span class="badge"><%= length(@groups) %></span>
    <% end %>
    <%= render_many @groups, Crm.ContactView, "_group.html", as: :group, conn: @conn, user_id: @current_user.id %>
  </div>
</div><!-- /.col-md-3 -->

<%= render "_form.html", changeset: @changeset,
                         action: contact_path(@conn, :update, @contact),
                         contact: @contact,
                         groups: @groups,
                         conn: @conn %>

web/templates/contact/groups.html.eex
<div class="row">
  <div class="col-md-3">
    <div class="list-group">
      <%= link "My Groups", to: contact_group_path(@conn, :index), class: "list-group-item" %>
      <%= link to: contact_path(@conn, :index), class: active_group?(@conn) do %>
        All Contacts
        <span class="badge"><%= @contacts_count %></span>
      <% end %>
      <%= render_many @groups, Crm.ContactView, "_group.html", as: :group, conn: @conn, user_id: @current_user.id %>
    </div>
  </div><!-- /.col-md-3 -->

  <div class="col-md-9">
    <div class="row <%= pack?(@contacts) %>">
      <%= render_many @contacts, Crm.ContactView, "_contact.html", conn: @conn, contacts: @contacts %>
    </div>

    <div class="text-center">
      <%= paginate @conn, @kerosene %>
    </div>
  </div>
</div>

web/templates/contact/index.html.eex
<div class="row">
  <div class="col-md-3">
    <div class="list-group">
      <%= link "My Groups", to: contact_group_path(@conn, :index), class: "list-group-item" %>
      <%= link to: contact_path(@conn, :index), class: active_group?(@conn) do %>
        All Contacts
        <span class="badge"><%= length(@contacts) %></span>
      <% end %>
      <%= render_many @groups, Crm.ContactView, "_group.html", as: :group, conn: @conn, user_id: @current_user.id %>
    </div>
  </div><!-- /.col-md-3 -->

  <div class="col-md-9">
    <div class="row <%= pack?(@contacts) %>">
      <%= render_many @contacts, Crm.ContactView, "_contact.html", conn: @conn, contacts: @contacts%>
    </div>

    <div class="text-center">
        <%= paginate @conn, @kerosene %>
    </div>
  </div>
</div>

web/templates/contact/new.html.eex
<div class="col-md-3">
  <div class="list-group">
    <%= link "My Groups", to: contact_group_path(@conn, :index), class: "list-group-item" %>
    <%= link to: contact_path(@conn, :index), class: active_group?(@conn) do %>
      All Contacts
      <span class="badge"><%= Crm.Contact.count(@current_user.id) %></span>
    <% end %>
    <div id="group_list">
    <%= render_many @groups, Crm.ContactView, "_group.html", as: :group, conn: @conn %>
    </div>
  </div>
</div><!-- /.col-md-3 -->

<%= render "_form.html", changeset: @changeset,
                         action: contact_path(@conn, :create),
                         groups: @groups,
                         conn: @conn %>

web/templates/contact/search.html.eex
<div class="row">
  <div class="col-md-3">
    <div class="list-group">
      <%= link "My Groups", to: contact_group_path(@conn, :index), class: "list-group-item" %>
      <%= link to: contact_path(@conn, :index), class: active_group?(@conn) do %>
        All Contacts
        <span class="badge"><%= @contacts_count %></span>
      <% end %>
      <%= render_many @groups, Crm.ContactView, "_group.html", as: :group, conn: @conn, user_id: @current_user.id %>
    </div>
  </div><!-- /.col-md-3 -->

  <div class="col-md-9">
    <div class="row <%= pack?(@contacts) %>">
      <%= if @contacts == [] do %>
        <h1>Nothing was found with that name</h1>
      <% else %>
        <%= render_many @contacts, Crm.ContactView, "_contact.html", conn: @conn, contacts: @contacts %>
    </div>

    <div class="text-center">
        <%= paginate @conn, @kerosene %>
    </div>
      <% end %>
  </div>
</div>

web/templates/contact/show.html.eex
<div class="row">
  <div class="col-md-3">
    <div class="list-group">
      <%= link to: contact_path(@conn, :index), class: active_group?(@conn) do %>
        All Contacts
        <span class="badge"><%= @contacts_count %></span>
      <% end %>
      <%= render_many @groups, Crm.ContactView, "_group.html", as: :group, conn: @conn, user_id: @current_user.id %>
    </div>
  </div><!-- /.col-md-3 -->

  <div class="col-md-5">
    <div id="contact-note-list" class="list-group">
      <%= render_many @notes, Crm.ContactView, "_note.html", as: :note %>
    </div>
    <div class="text-center">
        <%= paginate @conn, @kerosene %>
    </div>
  </div><!-- /.col-md-5 -->

  <%= render "_show_contact.html", conn: @conn, contact: @contact %>
</div>